.TH XGETIDLE 1 xgetidle\-VERSION
.SH NAME
xgetidle \- display the current X idle time
.SH SYNOPSIS
.B xgetidle 
.RB [ \-s ]
.RB [ \-v ]
.SH DESCRIPTION
.B xgetidle
will display the current idle time of X11 given the XScreenSaver extension.
.SH OPTIONS
.TP
.B \-s
display the result in seconds
.TP
.B \-v
show version information
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR slock (1)
.BR xlock (1)
.SH BUGS
Please report them.

